using Xunit;

namespace Goldpath.Cli.Tests;

/// <summary>
/// Mutation-killing companions to <see cref="AddWorkerTests"/>: every generated byte, every
/// refusal message and every process invocation is asserted EXACTLY — a skeleton that is
/// "almost right" compiles into an app that refuses to start (the launchSettings lesson).
/// </summary>
public class AddWorkerMutationTests
{
    private sealed record Result(int Code, string Output, string Error);

    private static Result Add(FakeApp app, IProcessRunner runner, string name, string trigger)
        => Add(app.Root, runner, name, trigger);

    private static Result Add(string root, IProcessRunner runner, string name, string trigger)
    {
        var output = new StringWriter();
        var error = new StringWriter();
        var code = CliRunner.Run(["add", "worker", name, "--trigger", trigger, "--path", root], runner, output, error);
        return new Result(code, output.ToString(), error.ToString());
    }

    private static string Line(string text) => text + Environment.NewLine;

    private static string Normalize(string text) => text.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string ProjectDir(FakeApp app, string projectName) => Path.Combine(app.Root, "src", projectName);

    // ── refusals: message + exit code, nothing written ──────────────────────────────────

    [Fact]
    public void Unknown_trigger_lists_the_accepted_ones()
    {
        using var app = new FakeApp();
        var result = Add(app, new FakeProcessRunner(), "payments", "cron");
        Assert.Equal(2, result.Code);
        Assert.Equal(Line("goldpath: unknown trigger 'cron' — one of: queue, schedule, jobs"), result.Error);
    }

    [Fact]
    public void A_directory_without_a_manifest_is_refused_with_the_path()
    {
        var bare = Path.Combine(Path.GetTempPath(), $"goldpath-cli-bare-{Guid.NewGuid():N}");
        Directory.CreateDirectory(bare);
        try
        {
            var result = Add(bare, new FakeProcessRunner(), "payments", "schedule");
            Assert.Equal(1, result.Code);
            var manifest = Path.Combine(bare, ".goldpath", "manifest.yaml");
            Assert.Equal(Line($"goldpath: no manifest at {manifest} — goldpath add runs inside a Goldpath-generated app (or pass --path)."), result.Error);
        }
        finally
        {
            Directory.Delete(bare, recursive: true);
        }
    }

    [Fact]
    public void A_worker_manifest_is_refused_by_its_kind()
    {
        using var app = new FakeApp(kind: "worker");
        var result = Add(app, new FakeProcessRunner(), "payments", "schedule");
        Assert.Equal(1, result.Code);
        Assert.Equal(Line("goldpath: this manifest is kind 'worker' — workers join a SOLUTION's AppHost; run goldpath add there."), result.Error);
    }

    [Fact]
    public void A_manifest_without_a_kind_is_reported_as_none()
    {
        using var app = new FakeApp();
        var lines = File.ReadAllLines(app.Manifest).Where(line => !line.StartsWith("kind:", StringComparison.Ordinal));
        File.WriteAllLines(app.Manifest, lines);

        var result = Add(app, new FakeProcessRunner(), "payments", "schedule");
        Assert.Equal(1, result.Code);
        Assert.Equal(Line("goldpath: this manifest is kind '<none>' — workers join a SOLUTION's AppHost; run goldpath add there."), result.Error);
    }

    [Fact]
    public void A_queue_worker_without_messaging_teaches_the_broker_seam()
    {
        using var app = new FakeApp();
        var result = Add(app, new FakeProcessRunner(), "payments", "queue");
        Assert.Equal(1, result.Code);
        Assert.Equal(Line("goldpath: a queue worker consumes from the broker — no AddGoldpathMessaging(...) found in the composition root. Wire messaging first (a broker resource + the AddGoldpathMessaging block), then re-run."), result.Error);
    }

    private static void DropConnectionString(FakeApp app)
        => File.WriteAllText(app.Program, app.Read(app.Program).Replace("var shopDbConnection = builder.Configuration.GetConnectionString(\"shopdb\");", string.Empty, StringComparison.Ordinal));

    [Theory]
    [InlineData("queue")]
    [InlineData("jobs")]
    public void A_persisting_worker_without_a_connection_name_is_refused(string trigger)
    {
        using var app = new FakeApp(messagingWired: true);
        DropConnectionString(app);
        var result = Add(app, new FakeProcessRunner(), "payments", trigger);
        Assert.Equal(1, result.Code);
        Assert.Equal(Line("goldpath: no GetConnectionString(...) found in the composition root — this worker persists into the app database and needs its connection name."), result.Error);
        Assert.False(Directory.Exists(ProjectDir(app, "Shop.PaymentsWorker")));
    }

    [Fact]
    public void A_schedule_worker_needs_no_connection_name()
    {
        using var app = new FakeApp();
        DropConnectionString(app);
        var result = Add(app, new FakeProcessRunner(), "cleanup", "schedule");
        Assert.Equal(0, result.Code);
        Assert.Equal(string.Empty, result.Error);
    }

    [Fact]
    public void An_existing_project_directory_is_refused_by_name()
    {
        using var app = new FakeApp();
        Directory.CreateDirectory(ProjectDir(app, "Shop.CleanupWorker"));
        var result = Add(app, new FakeProcessRunner(), "cleanup", "schedule");
        Assert.Equal(1, result.Code);
        Assert.Equal(Line("goldpath: src/Shop.CleanupWorker already exists — pick another name or remove it first."), result.Error);
    }

    [Fact]
    public void A_missing_solution_file_is_refused_before_anything_is_written()
    {
        using var app = new FakeApp();
        var appHostBefore = app.Read(app.AppHost);
        File.Delete(Path.Combine(app.Root, "Shop.sln"));
        var result = Add(app, new FakeProcessRunner(), "cleanup", "schedule");
        Assert.Equal(1, result.Code);
        Assert.Equal(Line("goldpath: no .sln at the app root — goldpath add worker wires the project into the solution."), result.Error);
        Assert.False(Directory.Exists(ProjectDir(app, "Shop.CleanupWorker")));
        Assert.Equal(appHostBefore, app.Read(app.AppHost));
    }

    [Fact]
    public void Two_solution_files_are_refused_with_the_count()
    {
        using var app = new FakeApp();
        File.WriteAllText(Path.Combine(app.Root, "Other.sln"), "");
        var result = Add(app, new FakeProcessRunner(), "cleanup", "schedule");
        Assert.Equal(1, result.Code);
        Assert.Equal(Line("goldpath: 2 .sln files at the app root — goldpath cannot choose; keep exactly one."), result.Error);
    }

    [Fact]
    public void A_name_without_letters_is_a_usage_error()
    {
        using var app = new FakeApp();
        var result = Add(app, new FakeProcessRunner(), "---", "schedule");
        Assert.Equal(2, result.Code);
        Assert.Equal(Line("goldpath: '---' does not yield a project name — use letters (e.g. payments, eod-report)."), result.Error);
        Assert.DoesNotContain(Directory.GetDirectories(Path.Combine(app.Root, "src")), d => d.EndsWith("Worker", StringComparison.Ordinal));
    }

    // ── the process seam: exact invocations, exact rollback ────────────────────────────

    [Fact]
    public void The_solution_entry_is_the_exact_dotnet_sln_add_call()
    {
        using var app = new FakeApp();
        // A second top-level file: only the *.sln pattern must find the solution.
        File.WriteAllText(Path.Combine(app.Root, "README.md"), "# Shop");
        var runner = new FakeProcessRunner();
        Assert.Equal(0, Add(app, runner, "cleanup", "schedule").Code);

        var sln = runner.Calls[0];
        Assert.Equal("dotnet", sln.FileName);
        Assert.Equal(
            ["sln", Path.Combine(app.Root, "Shop.sln"), "add", Path.Combine(app.Root, "src", "Shop.CleanupWorker", "Shop.CleanupWorker.csproj")],
            sln.Arguments);
        Assert.Equal(app.Root, sln.WorkingDirectory);

        // Then the engine, in order: validate, drift — both with the app root as CWD.
        Assert.Equal(3, runner.Calls.Count);
        Assert.Contains("validate", runner.Calls[1].Arguments);
        Assert.Equal(["drift", "--repo", "."], runner.Calls[2].Arguments.TakeLast(3));
        Assert.Equal(app.Root, runner.Calls[2].WorkingDirectory);
    }

    [Fact]
    public void A_failed_sln_add_restores_everything_and_says_so()
    {
        using var app = new FakeApp();
        var appHostBefore = app.Read(app.AppHost);
        var appHostProjectBefore = app.Read(app.AppHostProject);
        var runner = new FakeProcessRunner();
        runner.ExitCodeWhenArgumentsContain["sln"] = 1;

        var result = Add(app, runner, "cleanup", "schedule");
        Assert.Equal(1, result.Code);
        Assert.Equal(Line("goldpath: dotnet sln add failed — see its output above."), result.Error);
        Assert.Equal(string.Empty, result.Output);   // the engine never ran
        Assert.Single(runner.Calls);
        Assert.False(Directory.Exists(ProjectDir(app, "Shop.CleanupWorker")));
        Assert.Equal(appHostBefore, app.Read(app.AppHost));
        Assert.Equal(appHostProjectBefore, app.Read(app.AppHostProject));
    }

    [Fact]
    public void A_red_validate_skips_drift_and_reports_the_rollback()
    {
        using var app = new FakeApp();
        var runner = new FakeProcessRunner();
        runner.ExitCodeWhenArgumentsContain["validate"] = 1;

        var result = Add(app, runner, "cleanup", "schedule");
        Assert.Equal(1, result.Code);
        Assert.Equal(Line("goldpath: worker 'Shop.CleanupWorker' (schedule) wired — running the engine (specdrift validate + drift)"), result.Output);
        Assert.Equal(Line("goldpath: the engine rejected the result — ALL files restored; fix the findings above and retry (the worker was NOT added)."), result.Error);
        Assert.DoesNotContain(runner.Calls, c => c.Arguments.Contains("drift"));
    }

    [Fact]
    public void A_red_drift_after_a_green_validate_still_restores()
    {
        using var app = new FakeApp();
        var appHostBefore = app.Read(app.AppHost);
        var runner = new FakeProcessRunner();
        runner.ExitCodeWhenArgumentsContain["--repo"] = 1;   // `drift --repo .` (validate's `.specdrift/rules.yaml` would match "drift")

        var result = Add(app, runner, "cleanup", "schedule");
        Assert.Equal(1, result.Code);
        Assert.Contains(runner.Calls, c => c.Arguments.Contains("--repo"));   // drift DID run
        Assert.False(Directory.Exists(ProjectDir(app, "Shop.CleanupWorker")));
        Assert.Equal(appHostBefore, app.Read(app.AppHost));
        Assert.DoesNotContain("engine clean", result.Output, StringComparison.Ordinal);
    }

    // ── the success story: exact console, exact AppHost, exact project ─────────────────

    [Fact]
    public void Queue_success_prints_the_queue_decisions()
    {
        using var app = new FakeApp(messagingWired: true);
        var result = Add(app, new FakeProcessRunner(), "payments", "queue");
        Assert.Equal(0, result.Code);
        Assert.Equal(string.Empty, result.Error);
        Assert.Equal(
            Line("goldpath: worker 'Shop.PaymentsWorker' (queue) wired — running the engine (specdrift validate + drift)")
            + Line("goldpath: worker 'Shop.PaymentsWorker' added as resource 'payments-worker' — engine clean. Your decisions (goldpath never guesses domain opt-ins):")
            + Line("  → rename WorkItemQueued to the REAL upstream event (broker-bound contracts implement IIntegrationEvent — GP0401)")
            + Line("  → consuming an event the API publishes? the record moves to a shared <App>.Contracts classlib referenced by BOTH — events are wire contracts, never duplicated (docs/rfc/goldpath-event-contracts.md)")
            + Line("  → put the real work into the consumer; it commits WITH the inbox bookkeeping — exactly-once by construction")
            + Line("  → the worker owns its OWN tables' migrations: run `goldpath db add add-worker` and commit the migration"),
            result.Output);
    }

    [Fact]
    public void Schedule_success_prints_the_schedule_decisions()
    {
        using var app = new FakeApp();
        var result = Add(app, new FakeProcessRunner(), "cleanup", "schedule");
        Assert.Equal(0, result.Code);
        Assert.Equal(
            Line("goldpath: worker 'Shop.CleanupWorker' (schedule) wired — running the engine (specdrift validate + drift)")
            + Line("goldpath: worker 'Shop.CleanupWorker' added as resource 'cleanup-worker' — engine clean. Your decisions (goldpath never guesses domain opt-ins):")
            + Line("  → put the real work into IntervalJob.RunTickAsync (time-abstracted, directly testable); configure Worker:Interval")
            + Line("  → when the work outgrows a timer (chunks, resume, SLA), move to --trigger jobs — the Jobs module is the landing pad"),
            result.Output);
    }

    [Fact]
    public void Jobs_success_prints_the_jobs_decisions()
    {
        using var app = new FakeApp();
        var result = Add(app, new FakeProcessRunner(), "eod-report", "jobs");
        Assert.Equal(0, result.Code);
        Assert.Equal(
            Line("goldpath: worker 'Shop.EodReportWorker' (jobs) wired — running the engine (specdrift validate + drift)")
            + Line("goldpath: worker 'Shop.EodReportWorker' added as resource 'eod-report-worker' — engine clean. Your decisions (goldpath never guesses domain opt-ins):")
            + Line("  → replace NightlyReportJob's body with the real aggregation; review the cron and the Deadline (every job has an SLA — GP1302)")
            + Line("  → the worker runs its OWN fleet (SchedulerName) against the app database — the Api's scheduler is untouched; both consoles ride MapGoldpathJobsAdmin")
            + Line("  → the shared jobs tables stay the API context's migrations (the D3 exclusion is generated); run `goldpath db add add-worker` for the worker's PRIVATE tables"),
            result.Output);
    }

    private const string AppHostHead = """
        var builder = DistributedApplication.CreateBuilder(args);

        var database = builder.AddPostgres("dbserver").AddDatabase("shopdb");
        // goldpath:features resources — the drift profile is the source of these rows

        builder.AddProject<Projects.Shop_Api>("api")
            .WithReference(database).WaitFor(database)
            // goldpath:features references — the drift profile is the source of these rows
            .WithHttpHealthCheck("/health/ready");

        // goldpath:workers — additional worker projects wire here (goldpath add worker)


        """;   // the wiring block opens with an empty line — two newlines after the anchor

    private const string AppHostTail = """

        builder.Build().Run();
        """;

    [Fact]
    public void Queue_apphost_chains_database_then_messaging_then_probe()
    {
        using var app = new FakeApp(messagingWired: true);
        Assert.Equal(0, Add(app, new FakeProcessRunner(), "payments", "queue").Code);
        Assert.Equal(
            AppHostHead
            + "builder.AddProject<Projects.Shop_PaymentsWorker>(\"payments-worker\")\n"
            + "    .WithReference(database).WaitFor(database)\n"
            + "    .WithReference(messaging).WaitFor(messaging)\n"
            + "    .WithHttpHealthCheck(\"/health/ready\");\n"
            + AppHostTail,
            Normalize(app.Read(app.AppHost)));
    }

    [Fact]
    public void Jobs_apphost_chains_database_then_probe()
    {
        using var app = new FakeApp();
        Assert.Equal(0, Add(app, new FakeProcessRunner(), "eod-report", "jobs").Code);
        Assert.Equal(
            AppHostHead
            + "builder.AddProject<Projects.Shop_EodReportWorker>(\"eod-report-worker\")\n"
            + "    .WithReference(database).WaitFor(database)\n"
            + "    .WithHttpHealthCheck(\"/health/ready\");\n"
            + AppHostTail,
            Normalize(app.Read(app.AppHost)));
    }

    [Fact]
    public void Schedule_apphost_is_probe_only()
    {
        using var app = new FakeApp();
        Assert.Equal(0, Add(app, new FakeProcessRunner(), "cleanup", "schedule").Code);
        Assert.Equal(
            AppHostHead
            + "builder.AddProject<Projects.Shop_CleanupWorker>(\"cleanup-worker\")\n"
            + "    .WithHttpHealthCheck(\"/health/ready\");\n"
            + AppHostTail,
            Normalize(app.Read(app.AppHost)));
    }

    [Fact]
    public void The_apphost_project_reference_lands_right_after_the_workers_anchor()
    {
        using var app = new FakeApp();
        Assert.Equal(0, Add(app, new FakeProcessRunner(), "cleanup", "schedule").Code);
        Assert.Equal("""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup><IsAspireHost>true</IsAspireHost></PropertyGroup>
              <ItemGroup>
                <PackageReference Include="Aspire.Hosting.AppHost" />
                <!-- goldpath:features packages — the drift profile is the source of these rows -->
              </ItemGroup>
              <ItemGroup>
                <ProjectReference Include="../Shop.Api/Shop.Api.csproj" />
                <!-- goldpath:workers references — worker projects chain here (goldpath add worker) -->
                <ProjectReference Include="../Shop.CleanupWorker/Shop.CleanupWorker.csproj" />
              </ItemGroup>
            </Project>
            """, Normalize(app.Read(app.AppHostProject)));
    }

    // ── naming ─────────────────────────────────────────────────────────────────────────

    [Fact]
    public void A_web_project_not_named_Api_keeps_its_full_name_as_the_prefix()
    {
        using var app = new FakeApp();
        File.Move(app.ApiProject, Path.Combine(app.Root, "src", "Shop.Api", "Shopfront.csproj"));
        var runner = new FakeProcessRunner();
        var result = Add(app, runner, "payments", "schedule");
        Assert.Equal(0, result.Code);
        Assert.True(Directory.Exists(ProjectDir(app, "Shopfront.PaymentsWorker")));
        Assert.Contains("builder.AddProject<Projects.Shopfront_PaymentsWorker>(\"payments-worker\")", app.Read(app.AppHost), StringComparison.Ordinal);
    }

    [Fact]
    public void A_short_name_yields_a_short_kebab_resource()
    {
        using var app = new FakeApp();
        Assert.Equal(0, Add(app, new FakeProcessRunner(), "eod", "jobs").Code);
        Assert.True(Directory.Exists(ProjectDir(app, "Shop.EodWorker")));
        Assert.Contains("builder.AddProject<Projects.Shop_EodWorker>(\"eod-worker\")", app.Read(app.AppHost), StringComparison.Ordinal);
    }

    // ── the skeleton, byte for byte ────────────────────────────────────────────────────

    private static void AssertProjectIsExactly(string projectDir, IReadOnlyDictionary<string, string> expected)
    {
        var actual = Directory.EnumerateFiles(projectDir, "*", SearchOption.AllDirectories)
            .ToDictionary(path => Path.GetRelativePath(projectDir, path).Replace('\\', '/'), path => Normalize(File.ReadAllText(path)), StringComparer.Ordinal);
        Assert.Equal(expected.Keys.Order(StringComparer.Ordinal), actual.Keys.Order(StringComparer.Ordinal));
        foreach (var (file, content) in expected)
        {
            Assert.True(content == actual[file], $"{file} differs from the golden skeleton");
        }
    }

    [Fact]
    public void The_queue_skeleton_is_exactly_the_golden_one()
    {
        using var app = new FakeApp(messagingWired: true);
        Assert.Equal(0, Add(app, new FakeProcessRunner(), "payments", "queue").Code);
        AssertProjectIsExactly(ProjectDir(app, "Shop.PaymentsWorker"), QueueFiles);
    }

    [Fact]
    public void The_schedule_skeleton_is_exactly_the_golden_one()
    {
        using var app = new FakeApp();
        Assert.Equal(0, Add(app, new FakeProcessRunner(), "cleanup", "schedule").Code);
        AssertProjectIsExactly(ProjectDir(app, "Shop.CleanupWorker"), ScheduleFiles);
    }

    [Fact]
    public void The_jobs_skeleton_is_exactly_the_golden_one()
    {
        using var app = new FakeApp();
        Assert.Equal(0, Add(app, new FakeProcessRunner(), "eod-report", "jobs").Code);
        AssertProjectIsExactly(ProjectDir(app, "Shop.EodReportWorker"), JobsFiles);
    }

    [Fact]
    public void Sqlserver_swaps_exactly_the_provider_package()
    {
        using var app = new FakeApp(sqlServer: true);
        Assert.Equal(0, Add(app, new FakeProcessRunner(), "eod-report", "jobs").Code);
        var csproj = Normalize(File.ReadAllText(Path.Combine(ProjectDir(app, "Shop.EodReportWorker"), "Shop.EodReportWorker.csproj")));
        Assert.Equal(
            JobsFiles["Shop.EodReportWorker.csproj"].Replace("Npgsql.EntityFrameworkCore.PostgreSQL", "Microsoft.EntityFrameworkCore.SqlServer", StringComparison.Ordinal),
            csproj);
    }

    // Golden skeletons — what `goldpath add worker` ships for each trigger (the "Shop" fixture).

    private static readonly Dictionary<string, string> QueueFiles = new(StringComparer.Ordinal)
    {
        ["GlobalUsings.cs"] = """
            global using Goldpath;

            """,
        ["Program.cs"] = """
            using Shop.PaymentsWorker.WorkItems;
            using MassTransit;
            using Microsoft.EntityFrameworkCore;

            // A web host on purpose: readiness/liveness probes are the deployment contract of a
            // worker too — the HTTP surface carries probes, never business APIs.
            var builder = WebApplication.CreateBuilder(args);

            builder.AddGoldpathServiceDefaults();

            // Connection strings come from the AppHost; configuration stays tolerant, usage fails loudly.
            var workDbConnection = builder.Configuration.GetConnectionString("shopdb");
            builder.AddGoldpathData<WebApplicationBuilder, WorkDbContext>(options =>
            {
                // Design time (`dotnet ef`): the provider must BIND without a connection.
                if (workDbConnection is not null)
                {
                    options.UseNpgsql(workDbConnection);
                }
                else
                {
                    options.UseNpgsql();
                }
            });

            builder.AddGoldpathMessaging(bus =>
            {
                bus.AddConsumer<WorkItemQueuedConsumer>();
                // Consumer-side INBOX: every receive endpoint dedups on MessageId — exactly-once processing.
                bus.AddGoldpathOutbox<WorkDbContext>(outbox => outbox.UsePostgres());
                bus.UsingRabbitMq((context, cfg) =>
                {
                    if (builder.Configuration.GetConnectionString("messaging") is { } messagingConnection)
                    {
                        cfg.Host(new Uri(messagingConnection));
                    }

                    cfg.ConfigureGoldpathEndpoints(context);
                });
            });

            var app = builder.Build();

            app.MapGoldpathDefaultEndpoints();
            // Smoke-visible read model (what has been processed) — intentionally the only endpoint.
            app.MapGet("/api/v1/processed", async (WorkDbContext db) =>
                await db.ProcessedWorkItems.OrderBy(w => w.ProcessedAt).ToListAsync());

            app.Run();

            """,
        ["Properties/launchSettings.json"] = """
            {
              "$schema": "https://json.schemastore.org/launchsettings.json",
              "profiles": {
                "http": {
                  "commandName": "Project",
                  "dotnetRunMessages": true,
                  "launchBrowser": false,
                  "applicationUrl": "http://localhost:5409",
                  "environmentVariables": {
                    "ASPNETCORE_ENVIRONMENT": "Development"
                  }
                }
              }
            }

            """,
        ["Shop.PaymentsWorker.csproj"] = """
            <Project Sdk="Microsoft.NET.Sdk.Web">
              <!-- goldpath:worker-head — a web host for probes and the fleet console, never the Api (goldpath add worker) -->

              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Goldpath.Abstractions" />
                <PackageReference Include="Goldpath.ServiceDefaults" />
                <PackageReference Include="Goldpath.Data" />
                <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
                <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
                <PackageReference Include="Goldpath.Messaging" />
                <PackageReference Include="MassTransit.RabbitMQ" />
                <PackageReference Include="Goldpath.Analyzers" PrivateAssets="all" />
              </ItemGroup>

            </Project>

            """,
        ["WorkItems/ProcessedWorkItem.cs"] = """
            namespace Shop.PaymentsWorker.WorkItems;

            /// <summary>The durable result of one processed message — the walking skeleton's "work done" proof.</summary>
            public class ProcessedWorkItem
            {
                /// <summary>The upstream work-item identity (also the primary key: a natural dedup backstop).</summary>
                public Guid Id { get; set; }

                /// <summary>What was processed.</summary>
                public string Payload { get; set; } = string.Empty;

                /// <summary>When processing committed (UTC policy: DateTimeOffset).</summary>
                public DateTimeOffset ProcessedAt { get; set; }
            }

            """,
        ["WorkItems/WorkDbContext.cs"] = """
            using MassTransit;
            using Microsoft.EntityFrameworkCore;

            namespace Shop.PaymentsWorker.WorkItems;

            public class WorkDbContext(DbContextOptions<WorkDbContext> options) : DbContext(options)
            {
                public DbSet<ProcessedWorkItem> ProcessedWorkItems => Set<ProcessedWorkItem>();

                protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
                    => configurationBuilder.ApplyGoldpathConventions();

                protected override void OnModelCreating(ModelBuilder modelBuilder)
                {
                    modelBuilder.ApplyGoldpathModelDefaults();

                    // Inbox/outbox tables: the consumer-side dedup store (exactly-once processing).
                    modelBuilder.AddInboxStateEntity();
                    modelBuilder.AddOutboxMessageEntity();
                    modelBuilder.AddOutboxStateEntity();
                }
            }

            """,
        ["WorkItems/WorkItemQueued.cs"] = """
            namespace Shop.PaymentsWorker.WorkItems;

            /// <summary>
            /// The broker-bound contract this worker drains (implements <c>IIntegrationEvent</c> —
            /// GP0401). Rename/replace it with the real upstream event.
            /// </summary>
            public record WorkItemQueued(Guid WorkItemId, string Payload) : IIntegrationEvent;

            """,
        ["WorkItems/WorkItemQueuedConsumer.cs"] = """
            using MassTransit;

            namespace Shop.PaymentsWorker.WorkItems;

            /// <summary>
            /// The walking-skeleton consumer: inbox-guarded (exactly-once), commits its result in the
            /// same transaction as the dedup bookkeeping. Replace the body with the real work.
            /// </summary>
            public class WorkItemQueuedConsumer(WorkDbContext db) : IConsumer<WorkItemQueued>
            {
                /// <inheritdoc />
                public async Task Consume(ConsumeContext<WorkItemQueued> context)
                {
                    db.ProcessedWorkItems.Add(new ProcessedWorkItem
                    {
                        Id = context.Message.WorkItemId,
                        Payload = context.Message.Payload,
                        ProcessedAt = DateTimeOffset.UtcNow,
                    });
                    await db.SaveChangesAsync(context.CancellationToken);
                }
            }

            """,
    };

    private static readonly Dictionary<string, string> ScheduleFiles = new(StringComparer.Ordinal)
    {
        ["GlobalUsings.cs"] = """
            global using Goldpath;

            """,
        ["Jobs/IntervalJob.cs"] = """
            namespace Shop.CleanupWorker.Jobs;

            /// <summary>
            /// BCL <see cref="PeriodicTimer"/> skeleton (template-completion RFC D3): dependency-free
            /// scheduling that the Jobs module later replaces without touching the host shape. Put the
            /// actual work in <see cref="RunTickAsync"/>; keep the timer loop free of business logic.
            /// </summary>
            public sealed class IntervalJob(ILogger<IntervalJob> logger, IConfiguration configuration) : BackgroundService
            {
                /// <summary>Ticks executed so far (smoke-observable via /api/v1/ticks).</summary>
                public int TickCount { get; private set; }

                /// <inheritdoc />
                protected override async Task ExecuteAsync(CancellationToken stoppingToken)
                {
                    var interval = configuration.GetValue("Worker:Interval", TimeSpan.FromMinutes(1));
                    using var timer = new PeriodicTimer(interval);
                    while (await timer.WaitForNextTickAsync(stoppingToken))
                    {
                        await RunTickAsync();
                    }
                }

                /// <summary>One unit of scheduled work — replace the log line with the real job.</summary>
                public Task RunTickAsync()
                {
                    TickCount++;
                    logger.LogInformation("Interval tick {TickCount} executed.", TickCount);
                    return Task.CompletedTask;
                }
            }

            """,
        ["Program.cs"] = """
            using Shop.CleanupWorker.Jobs;

            // A web host on purpose: readiness/liveness probes are the deployment contract of a
            // worker too — the HTTP surface carries probes, never business APIs.
            var builder = WebApplication.CreateBuilder(args);

            builder.AddGoldpathServiceDefaults();

            builder.Services.AddSingleton<IntervalJob>();
            builder.Services.AddHostedService(sp => sp.GetRequiredService<IntervalJob>());

            var app = builder.Build();

            app.MapGoldpathDefaultEndpoints();
            // Smoke-visible tick counter — intentionally the only endpoint.
            app.MapGet("/api/v1/ticks", (IntervalJob job) => new { job.TickCount });

            app.Run();

            """,
        ["Properties/launchSettings.json"] = """
            {
              "$schema": "https://json.schemastore.org/launchsettings.json",
              "profiles": {
                "http": {
                  "commandName": "Project",
                  "dotnetRunMessages": true,
                  "launchBrowser": false,
                  "applicationUrl": "http://localhost:5362",
                  "environmentVariables": {
                    "ASPNETCORE_ENVIRONMENT": "Development"
                  }
                }
              }
            }

            """,
        ["Shop.CleanupWorker.csproj"] = """
            <Project Sdk="Microsoft.NET.Sdk.Web">
              <!-- goldpath:worker-head — a web host for probes and the fleet console, never the Api (goldpath add worker) -->

              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Goldpath.Abstractions" />
                <PackageReference Include="Goldpath.ServiceDefaults" />
                <PackageReference Include="Goldpath.Analyzers" PrivateAssets="all" />
              </ItemGroup>

            </Project>

            """,
    };

    private static readonly Dictionary<string, string> JobsFiles = new(StringComparer.Ordinal)
    {
        ["GlobalUsings.cs"] = """
            global using Goldpath;

            """,
        ["Program.cs"] = """
            using Shop.EodReportWorker.Reports;
            using Microsoft.EntityFrameworkCore;

            // A web host on purpose: readiness/liveness probes are the deployment contract of a
            // worker too — the HTTP surface carries probes (and the jobs console), never business APIs.
            var builder = WebApplication.CreateBuilder(args);

            builder.AddGoldpathServiceDefaults();

            // Connection strings come from the AppHost; configuration stays tolerant, usage fails loudly.
            var reportsDbConnection = builder.Configuration.GetConnectionString("shopdb");
            builder.AddGoldpathData<WebApplicationBuilder, ReportsDbContext>(options =>
            {
                // Design time (`dotnet ef`): the provider must BIND without a connection.
                if (reportsDbConnection is not null)
                {
                    options.UseNpgsql(reportsDbConnection);
                }
                else
                {
                    options.UseNpgsql();
                }
            });

            // Clustered jobs (Goldpath.Jobs) on the APP database, as this worker's OWN fleet: the
            // SchedulerName separates it from the Api's scheduler — same tables, two clusters,
            // zero contention for fires (one scheduler per PROCESS, one fleet per PURPOSE).
            builder.AddGoldpathJobs<WebApplicationBuilder, ReportsDbContext>(jobs =>
            {
                jobs.ConnectionName = "shopdb";
                jobs.SchedulerName = "shop-eodreportworker";
                jobs.AddJob<NightlyReportJob>(j =>
                {
                    j.Cron = "0 0 1 * * ?";                    // nightly at 01:00
                    j.Deadline = TimeSpan.FromHours(2);        // every job has an SLA (GP1302)
                    j.MaxParallelChunks = 2;
                });
            });

            var app = builder.Build();

            app.MapGoldpathDefaultEndpoints();
            app.MapGoldpathJobsAdmin<ReportsDbContext>(exposeUnsecured: true);   // internal fleet console — keep it behind the cluster boundary (H2 opt-out, visible)

            app.Run();

            """,
        ["Properties/launchSettings.json"] = """
            {
              "$schema": "https://json.schemastore.org/launchsettings.json",
              "profiles": {
                "http": {
                  "commandName": "Project",
                  "dotnetRunMessages": true,
                  "launchBrowser": false,
                  "applicationUrl": "http://localhost:5486",
                  "environmentVariables": {
                    "ASPNETCORE_ENVIRONMENT": "Development"
                  }
                }
              }
            }

            """,
        ["Reports/DailyReportRow.cs"] = """
            namespace Shop.EodReportWorker.Reports;

            /// <summary>One summarized day — the walking skeleton's "chunk did real work" proof.</summary>
            public class DailyReportRow
            {
                /// <summary>Day offset the row summarizes (the job's range payloads walk these).</summary>
                public int DayOffset { get; set; }

                /// <summary>When the summary was (re)generated (UTC policy: DateTimeOffset).</summary>
                public DateTimeOffset GeneratedAt { get; set; }
            }

            """,
        ["Reports/NightlyReportJob.cs"] = """
            using Microsoft.EntityFrameworkCore;
            using Microsoft.Extensions.DependencyInjection;

            namespace Shop.EodReportWorker.Reports;

            /// <summary>
            /// The walking-skeleton job: summarizes the last 30 days in 5-day CHUNKS. After every chunk
            /// the runner checkpoints — kill the pod mid-run and another node resumes where it stopped
            /// (never from the start). Replace the body with the real aggregation.
            /// </summary>
            public sealed class NightlyReportJob : IGoldpathJob
            {
                /// <inheritdoc />
                public Task<GoldpathJobPlan> PlanAsync(GoldpathJobContext context, CancellationToken cancellationToken)
                    => Task.FromResult(GoldpathJobPlanner.ByRange(totalItems: 30, chunkSize: 5));   // count, never materialize (GP1303)

                /// <inheritdoc />
                public async Task ExecuteChunkAsync(GoldpathJobChunk chunk, GoldpathJobContext context, CancellationToken cancellationToken)
                {
                    var db = context.Services.GetRequiredService<ReportsDbContext>();
                    var (start, endExclusive) = GoldpathJobPlanner.ParseRange(chunk.Payload);
                    for (var dayOffset = (int)start; dayOffset < endExclusive; dayOffset++)
                    {
                        var row = await db.DailyReports.FindAsync([dayOffset], cancellationToken)
                            ?? db.DailyReports.Add(new DailyReportRow { DayOffset = dayOffset }).Entity;
                        row.GeneratedAt = DateTimeOffset.UtcNow;
                    }

                    await db.SaveChangesAsync(cancellationToken);   // one batched write per chunk (house rule)
                }
            }

            """,
        ["Reports/ReportsDbContext.cs"] = """
            using Microsoft.EntityFrameworkCore;

            namespace Shop.EodReportWorker.Reports;

            public class ReportsDbContext(DbContextOptions<ReportsDbContext> options) : DbContext(options)
            {
                public DbSet<DailyReportRow> DailyReports => Set<DailyReportRow>();

                protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
                    => configurationBuilder.ApplyGoldpathConventions();

                protected override void OnModelCreating(ModelBuilder modelBuilder)
                {
                    modelBuilder.ApplyGoldpathModelDefaults();
                    modelBuilder.Entity<DailyReportRow>(report =>
                    {
                        report.HasKey(r => r.DayOffset);
                        // The key IS the day — never an identity (day 0 must not become "generated").
                        report.Property(r => r.DayOffset).ValueGeneratedNever();
                    });

                    // SHARED tables with the Api's fleet: the SchedulerName in Program.cs keeps
                    // the clusters apart, and the API'S context OWNS their migrations — this head
                    // maps them for querying only (one table set, ONE owner: migrations RFC D3).
                    modelBuilder.AddGoldpathJobs(excludeFromMigrations: true);
                }
            }

            """,
        ["Shop.EodReportWorker.csproj"] = """
            <Project Sdk="Microsoft.NET.Sdk.Web">
              <!-- goldpath:worker-head — a web host for probes and the fleet console, never the Api (goldpath add worker) -->

              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Goldpath.Abstractions" />
                <PackageReference Include="Goldpath.ServiceDefaults" />
                <PackageReference Include="Goldpath.Data" />
                <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
                <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
                <PackageReference Include="Goldpath.Jobs" />
                <PackageReference Include="Goldpath.Analyzers" PrivateAssets="all" />
              </ItemGroup>

            </Project>

            """,
    };
}
